version: '3.7'
services:
 client:
   build:
     context: client
   depends_on:
     - celery
 celery:
   image: celery
   build:
     context: celery
   depends_on:
     - redis
 redis:
   image: redis

